M_overload: /home/urbanjs/venus/V600/github/OVERLOAD/M_overload/src/source/recursive_bug_ifx.f90 File Reference
recursive_bug_ifx.f90 File Reference
Functions/Subroutines
program demo_trimzeros_
character(len=:) function, allocatable fmt (generic, format)
subroutine trimzeros_ (string)
Function/Subroutine Documentation
demo_trimzeros_()
program demo_trimzeros_
References fmt(), and trimzeros_().
fmt()
character(len=:) function, allocatable demo_trimzeros_::fmt (class(*), intent(in) generic, character(len=*), intent(in), optional format)
References trimzeros_().
trimzeros_()
subroutine demo_trimzeros_::trimzeros_ (character(len=*) string)